/**
 * Plane-of-array irradiance: extraterrestrial normal irradiance, angle of incidence, and
 * the Hay-Davies transposition of horizontal irradiance onto a tilted surface.
 *
 * Hand-ported to TypeScript per ADR 0003, transcribed from pvlib-python v0.15.2
 * `pvlib/irradiance.py` (BSD-3-Clause) — `get_extra_radiation(method='spencer')`,
 * `aoi_projection`, `aoi`, `haydavies`, `get_ground_diffuse` and `poa_components`, as
 * composed by `get_total_irradiance(model='haydavies')`. pvlib's numerical guards are
 * reproduced verbatim (and attributed to their upstream issue numbers) rather than
 * re-derived: the golden fixtures were generated by those exact functions, so a
 * "cleaner" guard here would simply be a divergence.
 *
 * Model references:
 *   - J. W. Spencer, "Fourier series representation of the position of the sun",
 *     Search 2(5), 172 (1971) — the eccentricity correction used for `dni_extra`.
 *   - J. E. Hay and J. A. Davies, "Calculations of the solar radiation incident on an
 *     inclined surface", Proc. First Canadian Solar Radiation Data Workshop, 59 (1980).
 *
 * This module deliberately does not import `solar-position.ts`: solar geometry enters as
 * plain angles, so the transposition can be exercised against reference angles without
 * dragging the SPA port in. Angles are degrees; irradiances are W/m². Surface azimuth
 * follows `siteSchema.azimuthDegrees` — clockwise from true north, 180 = due south.
 */

const toRadians = (degrees: number): number => (degrees * Math.PI) / 180;

const toDegrees = (radians: number): number => (radians * 180) / Math.PI;

/** pvlib `tools.cosd`: cosine of an angle given in degrees. */
const cosDeg = (degrees: number): number => Math.cos(toRadians(degrees));

/** pvlib `tools.sind`: sine of an angle given in degrees. */
const sinDeg = (degrees: number): number => Math.sin(toRadians(degrees));

const MILLISECONDS_PER_DAY = 86_400_000;

/**
 * Solar constant, W/m². pvlib's `get_extra_radiation` default, and the value pinned in
 * the golden-fixture generator.
 */
const SOLAR_CONSTANT_WM2 = 1366.1;

/**
 * Spencer's day angle divides by a fixed 365, never 366 — pvlib's
 * `solarposition._calculate_simple_day_angle` does the same, so leap years reuse the
 * common-year angle rather than rescaling.
 */
const SPENCER_DAY_ANGLE_DIVISOR_DAYS = 365;

/**
 * Floor applied to cos(zenith) in the Hay-Davies projection ratio (pvlib GH 432).
 * cos(89°) ≈ 0.01745, capping Rb near 57.3; the circumsolar term is DHI · A · Rb, so when
 * the anisotropy index A exceeds 1 (DNI above dni_extra) the multiple exceeds the Rb cap rather than
 * diverging as the sun reaches the horizon.
 */
const MINIMUM_COS_ZENITH_FOR_PROJECTION_RATIO = 0.01745;

/**
 * The 1-based UTC day of the year, matching pandas' `DatetimeIndex.dayofyear`, which is
 * what pvlib feeds to the Spencer day angle.
 *
 * `Date` is used purely as a calendar: the instant is a parameter, so this stays pure.
 */
const utcDayOfYear = (timeUtcMs: number): number => {
  const startOfYearUtcMs = Date.UTC(new Date(timeUtcMs).getUTCFullYear(), 0, 1);

  return Math.floor((timeUtcMs - startOfYearUtcMs) / MILLISECONDS_PER_DAY) + 1;
};

/**
 * Extraterrestrial irradiance normal to the sun at an instant, W/m², by Spencer's
 * eccentricity correction — pvlib `get_extra_radiation(method='spencer',
 * solar_constant=1366.1)`.
 *
 * Varies only with the day of the year: ~1414 W/m² near perihelion in early January and
 * ~1320 W/m² near aphelion in early July.
 */
export const extraterrestrialNormalIrradiance = (timeUtcMs: number): number => {
  const dayAngleRadians =
    ((2 * Math.PI) / SPENCER_DAY_ANGLE_DIVISOR_DAYS) * (utcDayOfYear(timeUtcMs) - 1);

  const radiusRatioSquared =
    1.00011 +
    0.034221 * Math.cos(dayAngleRadians) +
    0.00128 * Math.sin(dayAngleRadians) +
    0.000719 * Math.cos(2 * dayAngleRadians) +
    7.7e-5 * Math.sin(2 * dayAngleRadians);

  return SOLAR_CONSTANT_WM2 * radiusRatioSquared;
};

/** Where the sun is, and how the module faces, for one transposition. */
export interface SurfaceGeometry {
  /** Apparent (refraction-corrected) solar zenith angle, degrees from vertical. */
  readonly apparentZenithDeg: number;
  /** Solar azimuth, degrees clockwise from true north. */
  readonly solarAzimuthDeg: number;
  /** Module tilt from horizontal, degrees. */
  readonly tiltDegrees: number;
  /** Module azimuth, degrees clockwise from true north. */
  readonly azimuthDegrees: number;
}

/**
 * pvlib `aoi_projection`: the dot product of the sun vector and the surface normal, i.e.
 * cos(AOI). Negative when the sun is behind the plane of the module.
 *
 * The clip to [-1, 1] is pvlib's (GH 1185) and guards `acos` against rounding a
 * head-on sun to slightly more than 1.
 */
const aoiProjection = (geometry: SurfaceGeometry): number => {
  const { apparentZenithDeg, solarAzimuthDeg, tiltDegrees, azimuthDegrees } = geometry;

  const projection =
    cosDeg(tiltDegrees) * cosDeg(apparentZenithDeg) +
    sinDeg(tiltDegrees) * sinDeg(apparentZenithDeg) * cosDeg(solarAzimuthDeg - azimuthDegrees);

  return Math.min(Math.max(projection, -1), 1);
};

/**
 * Angle between the sun vector and the module's surface normal, degrees in [0, 180].
 * Greater than 90° means the sun is behind the module. pvlib `aoi`.
 */
export const angleOfIncidence = (geometry: SurfaceGeometry): number =>
  toDegrees(Math.acos(aoiProjection(geometry)));

/** Irradiance reaching the plane of the array, split into its three components. */
export interface PoaIrradiance {
  /** Direct beam on the plane of array, W/m². Zero when the sun is behind the module. */
  readonly beamWm2: number;
  /** Sky diffuse on the plane of array by Hay-Davies (isotropic + circumsolar), W/m². */
  readonly skyDiffuseWm2: number;
  /** Ground-reflected diffuse on the plane of array, W/m². */
  readonly groundWm2: number;
  /** Total plane-of-array irradiance, W/m² — the sum of the three components. */
  readonly totalWm2: number;
}

/** Everything one plane-of-array transposition needs. */
export interface PoaIrradianceInput extends SurfaceGeometry {
  /** Global horizontal irradiance, W/m². Drives the ground-reflected term. */
  readonly ghiWm2: number;
  /** Direct normal irradiance, W/m². */
  readonly dniWm2: number;
  /** Diffuse horizontal irradiance, W/m². */
  readonly dhiWm2: number;
  /** Extraterrestrial normal irradiance, W/m² — from `extraterrestrialNormalIrradiance`. */
  readonly dniExtraWm2: number;
  /** Ground reflectance, 0–1. */
  readonly albedo: number;
}

/**
 * Plane-of-array irradiance for a tilted surface — pvlib
 * `get_total_irradiance(model='haydavies')`, component for component.
 *
 * Hay-Davies splits the sky diffuse into a circumsolar part, weighted by the anisotropy
 * index `A = DNI / DNI_extra` and projected onto the plane by `Rb`, and an isotropic
 * remainder over the sky dome. The ground term is isotropic. Both the isotropic and
 * circumsolar sky terms are floored at zero by pvlib, which matters when DNI exceeds the
 * extraterrestrial irradiance (`A > 1`) in noisy measured data.
 */
export const poaIrradiance = (input: PoaIrradianceInput): PoaIrradiance => {
  const { ghiWm2, dniWm2, dhiWm2, dniExtraWm2, tiltDegrees, apparentZenithDeg, albedo } = input;

  // pvlib GH 526: the beam projection is floored at zero before forming Rb, so a sun
  // behind the module contributes no circumsolar diffuse instead of a negative one.
  const cosIncidenceForProjection = Math.max(aoiProjection(input), 0);
  const projectionRatio =
    cosIncidenceForProjection /
    Math.max(cosDeg(apparentZenithDeg), MINIMUM_COS_ZENITH_FOR_PROJECTION_RATIO);

  const anisotropyIndex = dniWm2 / dniExtraWm2;
  const skyDomeViewFactor = 0.5 * (1 + cosDeg(tiltDegrees));

  const isotropicWm2 = Math.max(dhiWm2 * (1 - anisotropyIndex) * skyDomeViewFactor, 0);
  const circumsolarWm2 = Math.max(dhiWm2 * (anisotropyIndex * projectionRatio), 0);
  const skyDiffuseWm2 = isotropicWm2 + circumsolarWm2;

  const groundWm2 = ghiWm2 * albedo * (1 - cosDeg(tiltDegrees)) * 0.5;

  // pvlib's `poa_components` takes AOI in degrees and re-cosines it rather than reusing
  // the projection; keeping that round trip keeps this port bit-identical to the fixtures.
  const beamWm2 = Math.max(dniWm2 * cosDeg(angleOfIncidence(input)), 0);

  return {
    beamWm2,
    skyDiffuseWm2,
    groundWm2,
    totalWm2: beamWm2 + skyDiffuseWm2 + groundWm2,
  };
};
