import type { ApiErrorCode } from '@cumulo/shared';

import {
  DEFAULT_FORECAST_HORIZON_HOURS,
  FORECAST_HORIZON_HOURS,
} from '../forecast/get-site-forecast';
import { MAX_SERIES_SPAN_HOURS } from '../forecast/get-site-series';
import { apiErrorStatus } from '../http/response';
import { siteIdParamName } from '../sites/site-id-param';

import { componentRef, type ComponentSchemaName } from './components';
import { docsAssetParamName, docsAssetContentTypes } from './docs-assets';
import type {
  ContentObject,
  ParameterObject,
  PathsObject,
  ResponseObject,
  ResponsesObject,
  SchemaObject,
} from './openapi-types';

/**
 * The `paths` half of the document: one entry per route in `main.ts`'s table.
 *
 * Two properties are held by construction rather than by proof-reading.
 *
 * **Statuses are read, not restated.** Every `apiErrorSchema` response below is
 * keyed by `apiErrorStatus[code]` — the same map `errorResponse` derives a
 * status line from. A document that hard-coded `'404'` beside `not_found` would
 * be a second statement of the error contract, free to disagree with the first
 * one the day it changed.
 *
 * **Names are checked.** Path parameters take their names from the router's own
 * constants (`siteIdParamName`, `docsAssetParamName`) and every schema position
 * is a `componentRef`, so a renamed parameter or component is a type error here
 * rather than a `$ref` into nothing.
 *
 * `document.test.ts` closes the remaining gap — that the set of documented
 * operations equals the set of registered routes — by walking the live route
 * table rather than a list copied into a test.
 */

const jsonContent = (schema: SchemaObject): ContentObject => ({
  'application/json': { schema },
});

const componentResponse = (description: string, name: ComponentSchemaName): ResponseObject => ({
  description,
  content: jsonContent(componentRef(name)),
});

/**
 * What each error code means to a caller, once, since the same sentences would
 * otherwise be retyped on ten operations.
 *
 * Exhaustive by type (`Record<ApiErrorCode, string>`), which is the mechanism
 * that keeps it honest: a code added to `apiErrorCodeSchema` in `@cumulo/shared`
 * is a type error here until someone decides what it means to a caller, rather
 * than a code that reaches the published document undocumented.
 */
const apiErrorDescriptions: Record<ApiErrorCode, string> = {
  validation_failed:
    'The request was rejected before anything was read. `details` names the fields at fault.',
  forbidden: [
    'Refused on policy rather than on content — the request is well-formed, but this',
    'deployment does not serve it from where it came from. No credential makes it',
    'succeed; there are none to present.',
  ].join(' '),
  not_found: 'No such resource. An unknown route and an unknown site id both answer this way.',
  rate_limited: [
    'Refused by this service’s own rate limiter. `retry-after` names the wait in seconds.',
    'The other 429 below is API Gateway’s throttle, which answers before this service',
    'is invoked and does not use this body shape.',
  ].join(' '),
  internal:
    'Something failed that this service did not predict. The detail is in the log, not in the body.',
};

const errorResponses = (...codes: readonly ApiErrorCode[]): ResponsesObject =>
  Object.fromEntries(
    codes.map((code) => [
      String(apiErrorStatus[code]),
      componentResponse(apiErrorDescriptions[code], 'ApiError'),
    ]),
  );

/**
 * The 429 every operation can answer, and the one error in this document that
 * is not an `ApiError`.
 *
 * It is generated by API Gateway's stage throttle (ADR 0005: rate 10/s, burst
 * 20) *before* this Lambda is invoked, so the body is the gateway's own
 * `{ "message": … }` and no code in this repository can shape it. Documenting
 * the real body rather than the one we would have preferred is the point:
 * clients are told, here and in `ApiError`'s description, to map on status.
 */
const throttledResponse: ResponsesObject = {
  '429': {
    description: [
      'Throttled by the API Gateway stage (10 requests/second, burst 20). Generated by',
      'the gateway, so this is the only error whose body is not an ApiError — retry',
      'after a short pause.',
    ].join(' '),
    content: jsonContent({
      type: 'object',
      properties: { message: { type: 'string' } },
      required: ['message'],
    }),
  },
};

/** The two failures every operation shares, whatever it does. */
const commonFailures: ResponsesObject = { ...throttledResponse, ...errorResponses('internal') };

const siteIdParameter: ParameterObject = {
  name: siteIdParamName,
  in: 'path',
  required: true,
  description: 'The server-assigned site id, as returned by `POST /v1/sites`.',
  schema: { type: 'string', format: 'uuid' },
};

const forecastHoursParameter: ParameterObject = {
  name: 'hours',
  in: 'query',
  required: false,
  description: [
    'How far forward to read. A closed set rather than a free integer, because each',
    'value is a read whose cost is known in advance.',
  ].join(' '),
  schema: {
    type: 'string',
    enum: [...FORECAST_HORIZON_HOURS],
    default: DEFAULT_FORECAST_HORIZON_HOURS,
  },
};

const seriesBoundParameter = (name: 'from' | 'to', bound: string): ParameterObject => ({
  name,
  in: 'query',
  required: true,
  description: [
    `The ${bound} of the window, as a whole-second UTC timestamp (\`2026-07-31T09:00:00Z\`).`,
    `\`from\` must be strictly before \`to\`, and the window may not exceed ${String(MAX_SERIES_SPAN_HOURS)} hours —`,
    'a bound on what one request can make this API read.',
  ].join(' '),
  schema: { type: 'string', format: 'date-time' },
});

const createSiteBody = {
  description: 'The site to add. Any `id` in the body is ignored — the server assigns one.',
  required: true,
  content: jsonContent(componentRef('CreateSiteInput')),
};

/** `text/css` and friends, as the 200 of the asset route. */
const docsAssetContent: ContentObject = Object.fromEntries(
  docsAssetContentTypes.map((contentType) => [contentType, { schema: { type: 'string' } }]),
);

export const apiPaths: PathsObject = {
  '/v1/sites': {
    get: {
      operationId: 'listSites',
      summary: 'List the fleet',
      description: [
        'Every site, seed and user-created, active and inactive. Unpaginated by design:',
        'the fleet lives in one partition and #29 caps how many user sites can exist, so',
        '"the whole fleet" is a bounded answer.',
      ].join(' '),
      responses: {
        '200': componentResponse('The whole fleet.', 'ListSitesResponse'),
        ...commonFailures,
      },
    },
    post: {
      operationId: 'createSite',
      summary: 'Add a site to the fleet',
      description: [
        'Unauthenticated on purpose — this is the demo\'s "add a site" flow. The server',
        'assigns `id`, sets `origin` to `user`, stamps `createdAt` and marks the site',
        'active; the 201 body is the only place the caller learns the new id.',
      ].join(' '),
      requestBody: createSiteBody,
      responses: {
        '201': componentResponse('The site as stored, including its new id.', 'FleetSite'),
        ...errorResponses('validation_failed'),
        ...commonFailures,
      },
    },
  },
  '/v1/sites/{siteId}': {
    get: {
      operationId: 'getSite',
      summary: 'Read one site',
      description: 'The stored site, or 404 if no site has that id.',
      parameters: [siteIdParameter],
      responses: {
        '200': componentResponse('The site.', 'FleetSite'),
        ...errorResponses('validation_failed', 'not_found'),
        ...commonFailures,
      },
    },
    put: {
      operationId: 'updateSite',
      summary: 'Replace one site',
      description: [
        "A full replace of the caller-settable fields; the site's `id`, `origin`,",
        '`createdAt` and `active` are preserved from the stored row. Last write wins —',
        'there is no optimistic concurrency on this endpoint.',
      ].join(' '),
      parameters: [siteIdParameter],
      requestBody: createSiteBody,
      responses: {
        '200': componentResponse('The site as stored after the replace.', 'FleetSite'),
        ...errorResponses('validation_failed', 'not_found'),
        ...commonFailures,
      },
    },
    delete: {
      operationId: 'deleteSite',
      summary: 'Remove a site from the fleet',
      description: [
        "Removes the site row. The site's stored series rows are left to expire under",
        'their retention TTL; range-deleting them is #29.',
      ].join(' '),
      parameters: [siteIdParameter],
      responses: {
        '204': { description: 'The site is gone. No body.' },
        ...errorResponses('validation_failed', 'not_found'),
        ...commonFailures,
      },
    },
  },
  '/v1/sites/{siteId}/forecast': {
    get: {
      operationId: 'getSiteForecast',
      summary: 'Forecast for one site, from now forward',
      description: [
        'Reads stored forecast points from the current time forward. **An empty',
        '`forecasts` array is a 200, not a 404**: a site created moments ago has no',
        'points until the next forecast cycle writes them, which is a fact about the',
        "fleet's schedule and not about whether the site exists. A client polling for a",
        'first forecast should treat `[]` as "keep waiting" and 404 as "stop". Every',
        'response carries the Open-Meteo attribution that must be displayed with the',
        'data; this endpoint makes no upstream weather calls of its own.',
      ].join(' '),
      parameters: [siteIdParameter, forecastHoursParameter],
      responses: {
        '200': componentResponse(
          'Forecast points for the requested horizon, possibly empty, with attribution.',
          'SiteForecastResponse',
        ),
        ...errorResponses('validation_failed', 'not_found'),
        ...commonFailures,
      },
    },
  },
  '/v1/sites/{siteId}/series': {
    get: {
      operationId: 'getSiteSeries',
      summary: 'Forecasts and actuals for one site over a window',
      description: [
        'One read of the stored series, split into the forecasts and the measured',
        'actuals over the same window, for plotting the two against each other. An empty',
        'window is a 200 with empty arrays; only an unknown site id is a 404. Carries the',
        'Open-Meteo attribution that must be displayed with the data.',
      ].join(' '),
      parameters: [
        siteIdParameter,
        seriesBoundParameter('from', 'start'),
        seriesBoundParameter('to', 'end'),
      ],
      responses: {
        '200': componentResponse(
          'Forecasts and actuals over the window, with attribution.',
          'SiteSeriesResponse',
        ),
        ...errorResponses('validation_failed', 'not_found'),
        ...commonFailures,
      },
    },
  },
  '/openapi.json': {
    get: {
      operationId: 'getOpenApiDocument',
      summary: 'This document',
      description: [
        'The OpenAPI 3.0 document, generated at start-up from the same zod schemas the',
        'handlers validate against. There is no spec file in the repository to drift.',
      ].join(' '),
      responses: {
        '200': { description: 'The OpenAPI document.', content: jsonContent({ type: 'object' }) },
        ...commonFailures,
      },
    },
  },
  '/docs': {
    get: {
      operationId: 'getDocsPage',
      summary: 'Swagger UI',
      description: [
        'The API reference, served from this same Lambda with version-pinned assets',
        'bundled into its deployment artifact (ADR 0005). Same origin as the API, so',
        '"try it out" issues real requests with no CORS negotiation.',
      ].join(' '),
      responses: {
        '200': {
          description: 'The Swagger UI page.',
          content: { 'text/html': { schema: { type: 'string' } } },
        },
        ...commonFailures,
      },
    },
  },
  '/docs/{asset}': {
    get: {
      operationId: 'getDocsAsset',
      summary: 'A Swagger UI asset',
      description: [
        'Serves one file from a fixed allowlist of bundled Swagger UI assets. The name',
        'is matched against that allowlist and never used to build a path, so there is no',
        'traversal to defend against; anything not on the list is a 404.',
      ].join(' '),
      parameters: [
        {
          name: docsAssetParamName,
          in: 'path',
          required: true,
          description: 'The exact file name of an allowlisted asset.',
          schema: { type: 'string' },
        },
      ],
      responses: {
        '200': { description: 'The asset.', content: docsAssetContent },
        ...errorResponses('not_found'),
        ...commonFailures,
      },
    },
  },
};
