import { useEffect, useRef, type ReactElement } from 'react';

import { syncDialogOpen } from '../dialog-modality';
import { AddSiteForm, type AddSiteFormProps } from './AddSiteForm';

export interface AddSiteDialogProps extends AddSiteFormProps {
  /**
   * Puts focus back where the reader came from, once this dialog has left the
   * document.
   *
   * A callback rather than an element, because the control it lands on belongs
   * to the map (`map/MapControls.tsx`) and this dialog has no business holding a
   * handle to it. The dashboard owns both and is the one place that can say
   * where focus goes.
   */
  readonly onReturnFocus: () => void;
}

/**
 * The add-site form, as a modal.
 *
 * ## Why the form moved off the page
 *
 * Placing a site is a short, committed detour: the reader has armed the map,
 * picked a spot, and now answers four questions. As a panel in the reading
 * column it competed with the fleet and the site panel for one region, which
 * made "a draft outranks a selection" a precedence rule the composition had to
 * state and the reader had to infer. A modal makes that precedence physical —
 * the page behind is inert, so there is nothing to outrank — and it stops the
 * form being written into a region that may be scrolled off screen.
 *
 * ## Mount is open, unmount is closed
 *
 * Unlike `header/AboutDialog.tsx`, this one takes no `open` prop: the dashboard
 * renders it only while there is a draft, keyed on the draft's coordinates. That
 * key is load-bearing and predates this dialog — `AddSiteForm` reads the
 * coordinates once at mount, so a new location has to *remount* it rather than
 * re-render it (`react.md` rule 1, in place of an effect resetting the fields).
 * Mounting the dialog with the draft keeps that one mechanism instead of adding
 * a second, separately-owned open flag that could disagree with it.
 *
 * The cost of closing by unmount rather than by `close()` is the one thing the
 * platform then stops doing for us: a dialog that is *removed* never runs the
 * close steps, so the browser never restores focus. `onReturnFocus` is that
 * piece, supplied by hand — and it fires from the effect's cleanup rather than
 * from a click handler on purpose. On the Escape path the browser's own
 * restoration runs while the `cancel` event is still being dispatched, so a
 * focus call made there would be immediately overwritten; a cleanup runs after
 * React has committed the unmount, which is after the browser has finished.
 *
 * `cancel` is the element telling us it has been dismissed. It is not
 * prevented — letting the browser run its own close steps is what keeps Escape
 * meaning what it means everywhere else.
 *
 * ## One known gap, stated rather than papered over
 *
 * The `<dialog>` itself carries no `aria-labelledby`. The heading that would
 * name it belongs to `AddSiteForm`, whose id is generated by its own `useId`
 * and not exposed, and the alternatives are both worse: an `aria-label` here
 * would be a second copy of the words "Add a site", free to drift from the
 * heading it restates (`structure.md` rule 7). What a reader gets instead is
 * that heading, focused by the form's own mount effect, so the first thing
 * announced on open is the dialog's subject. Closing the gap properly means
 * `AddSiteForm` accepting the id — a change to a component this chunk was
 * scoped to leave alone, and recorded in `docs/tech-debt.md` ("The app's two
 * native dialogs disagree about whether a modal names itself") because
 * `header/AboutDialog.tsx` answers the same question the other way.
 */
export const AddSiteDialog = ({ onReturnFocus, ...form }: AddSiteDialogProps): ReactElement => {
  const dialogRef = useRef<HTMLDialogElement>(null);

  /*
   * The latest return-focus callback without making it a dependency of the
   * effect below (`react.md` rule 2's ref pattern). It has to stay out of the
   * deps: this effect runs once, and its cleanup *is* the close — re-running it
   * because the dashboard re-rendered would close and reopen the dialog under
   * the reader.
   */
  const onReturnFocusRef = useRef(onReturnFocus);
  onReturnFocusRef.current = onReturnFocus;

  // The element's open-ness is an external system — a top layer, a backdrop, an
  // inert page and a focus stack all live in the DOM rather than in React
  // (`react.md` rule 1). Empty deps because mount is the whole of "open".
  useEffect(() => {
    const dialog = dialogRef.current;

    if (dialog !== null) {
      syncDialogOpen(dialog, true);
    }

    return () => {
      onReturnFocusRef.current();
    };
  }, []);

  return (
    <dialog className="add-site-dialog" ref={dialogRef} onCancel={form.onCancel}>
      <AddSiteForm {...form} />
    </dialog>
  );
};
